# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roboUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoboUI(object):
    def setupUi(self, RoboUI):
        RoboUI.setObjectName("RoboUI")
        RoboUI.resize(1128, 828)
        self.centralwidget = QtWidgets.QWidget(RoboUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1111, 851))
        self.label.setText("")
        script_dir = os.path.dirname(os.path.abspath(__file__))
        self.label.setPixmap(QtGui.QPixmap(os.path.join(script_dir,"Black_Template.jpg")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 0, 541, 401))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(os.path.join(script_dir,"Iron_Template_1.gif")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 200, 451, 311))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(os.path.join(script_dir,"__1.gif")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 421, 261))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(os.path.join(script_dir,"initial.gif")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 550, 331, 231))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(os.path.join(script_dir,"Health_Template.gif")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(580, 460, 521, 351))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(os.path.join(script_dir,"B.G_Template_1.gif")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 580, 141, 81))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 700, 141, 81))
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 0);\n"
"color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        RoboUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(RoboUI)
        QtCore.QMetaObject.connectSlotsByName(RoboUI)

    def retranslateUi(self, RoboUI):
        _translate = QtCore.QCoreApplication.translate
        RoboUI.setWindowTitle(_translate("RoboUI", "MainWindow"))
        self.pushButton.setText(_translate("RoboUI", "START"))
        self.pushButton_2.setText(_translate("RoboUI", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RoboUI = QtWidgets.QMainWindow()
    ui = Ui_RoboUI()
    ui.setupUi(RoboUI)
    RoboUI.show()
    sys.exit(app.exec_())
